homepage:
    pattern:  /
    defaults: { _controller: {{ appname }}Bundle:{{ controller }}:welcome }

{{ appname }}:
    pattern:  /{{ controller }}
    defaults: { _controller: {{ appname }}Bundle:{{ controller }}:index }
