#!/usr/bin/env php
<?php
require 'Symfony/Component/ClassLoader/UniversalClassLoader.php';

/**
 * symfony2project
 *
 * @author      Bertrand Zuchuat <bertrand.zuchuat@gmail.com>
 */

use Symfony\Component\ClassLoader\UniversalClassLoader;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Input\StringInput;
use Command\GenerateProjectCommand;

$loader = new UniversalClassLoader();
$loader->registerNamespaces(array(
  'Command'         => __DIR__,
  'Symfony'         => __DIR__,
  'Installer'       => __DIR__,
  ));
$loader->register();

$application = new Application('symfony2project', '1.0');
$application->add(new GenerateProjectCommand());
$application->run();
